/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.StockIs.view;

import com.StockIs.controller.ValidationUtil;
import com.StockIs.model.stockModel;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author prashantrijal
 */
public class StockApp extends javax.swing.JFrame {
    private List<stockModel> stockList;
    private java.awt.CardLayout cardLayout;
    private ValidationUtil validator; 

    /**
     * Creates new form StockIs
     */
    public StockApp() {
        initComponents();
        initializeLayout(); //Setup card layout and screens
        initializeData();
    }
    
    private void initializeLayout() {
            cardLayout = new java.awt.CardLayout();
            getContentPane().setLayout(cardLayout);

            // Add panels with unique identifiers
            getContentPane().add(LoginPanel,"LoginScreen" );
            getContentPane().add(HomePanel,"HomeScreen" );
    }
    
    private void loadScreen(String screenName) {
        cardLayout.show(getContentPane(), screenName);
    }
    
    private void initializeData() {
        stockList = new LinkedList();
        registerStock(new stockModel("1234", "Suman", "Equity", "2005-12-23", 56789, 234,345));
        registerStock(new stockModel("12345", "Raman", "Equity", "2005-12-23", 56789, 456,789));
    }
    
    private void registerStock(stockModel stock) {
        stockList.add(stock);
        DefaultTableModel model = (DefaultTableModel) TblStock.getModel(); // Create a table model for inputting data in table
        TblStock.setModel(model);
        model.addRow(new Object[]{
            stock.getStockId(), stock.getName(), stock.getType(),stock.getListingDate(), stock.getTotalShares(), stock.getOpenPrice(), stock.getClosePrice()
        });
    }
    private void loadListToTable(List<stockModel> stockList) {
        DefaultTableModel model = (DefaultTableModel) TblStock.getModel();

        // Clear existing rows if needed
        model.setRowCount(0);

        // Populate the table with student data
        stockList.forEach(stock -> model.addRow(new Object[]{
            stock.getStockId(),
            stock.getName(),
            stock.getType(),
            stock.getListingDate(),
            stock.getTotalShares(),
            stock.getOpenPrice(),
            stock.getClosePrice()
        }));
    }
    private boolean checkDuplicateStock(stockModel stock) {
        return stockList.stream()
                .anyMatch(existingStock
                        -> (existingStock.getStockId() == null ? stock.getStockId() == null : existingStock.getStockId().equals(stock.getStockId())));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomePanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        HomeLbl = new javax.swing.JLabel();
        AddLbl = new javax.swing.JLabel();
        UpdateLbl = new javax.swing.JLabel();
        DeleteLbl = new javax.swing.JLabel();
        TabbedPanel = new javax.swing.JTabbedPane();
        HomePnl = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TblStock = new javax.swing.JTable();
        AddPnl = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        TxtCompanyName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TxtTotalShares = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TxtClosePrice = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TxtOpenPrice = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        TxtType = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TxtListingDate = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TxtStockId = new javax.swing.JTextField();
        AddBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        UpdatePnl = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        UpdateBtn = new javax.swing.JButton();
        OpenPriceTxt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        ListingDateTxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        TypeTxt = new javax.swing.JTextField();
        CompanyNameTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        StockIdTxt = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        ClosePriceTxt = new javax.swing.JTextField();
        TotalSharesTxt = new javax.swing.JTextField();
        LoginPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        UsernameTxt = new javax.swing.JTextField();
        PasswordTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        HomePanel.setMaximumSize(new java.awt.Dimension(1110, 700));
        HomePanel.setMinimumSize(new java.awt.Dimension(1110, 700));
        HomePanel.setPreferredSize(new java.awt.Dimension(1110, 700));
        HomePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(140, 151, 157));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/StockIs/resource/LogoSmall.png"))); // NOI18N

        HomeLbl.setBackground(new java.awt.Color(140, 151, 157));
        HomeLbl.setForeground(new java.awt.Color(255, 255, 255));
        HomeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/StockIs/resource/HomeIcon.png"))); // NOI18N
        HomeLbl.setText("  HOME");
        HomeLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeLblMouseCLicked(evt);
            }
        });

        AddLbl.setBackground(new java.awt.Color(140, 151, 157));
        AddLbl.setForeground(new java.awt.Color(255, 255, 255));
        AddLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/StockIs/resource/AddIcon.png"))); // NOI18N
        AddLbl.setText("   ADD");
        AddLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddLblMouseClicked(evt);
            }
        });

        UpdateLbl.setBackground(new java.awt.Color(140, 151, 157));
        UpdateLbl.setForeground(new java.awt.Color(255, 255, 255));
        UpdateLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/StockIs/resource/UpdateIcon.png"))); // NOI18N
        UpdateLbl.setText("  UPDATE");
        UpdateLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateLblMouseClicked(evt);
            }
        });

        DeleteLbl.setBackground(new java.awt.Color(140, 151, 157));
        DeleteLbl.setForeground(new java.awt.Color(255, 255, 255));
        DeleteLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/StockIs/resource/DeleteIcon.png"))); // NOI18N
        DeleteLbl.setText("DELETE");
        DeleteLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(HomeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UpdateLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DeleteLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AddLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(UpdateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(DeleteLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        HomePanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 839));

        HomePnl.setBackground(new java.awt.Color(188, 204, 220));

        TblStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Stock Id", "Company Name", "Type", "Listing Date", "Total Shares", "Open Price", "Close Price"
            }
        ));
        jScrollPane4.setViewportView(TblStock);

        javax.swing.GroupLayout HomePnlLayout = new javax.swing.GroupLayout(HomePnl);
        HomePnl.setLayout(HomePnlLayout);
        HomePnlLayout.setHorizontalGroup(
            HomePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePnlLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        HomePnlLayout.setVerticalGroup(
            HomePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePnlLayout.createSequentialGroup()
                .addContainerGap(264, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        TabbedPanel.addTab("tab1", HomePnl);

        jLabel7.setText("Company Name");

        jLabel8.setText("Total Shares");

        jLabel11.setText("Open Price");

        jLabel13.setText("Close Price");

        jLabel15.setText("Type");

        jLabel16.setText("Listing Date");

        jLabel17.setText("Stock Id");

        TxtStockId.setToolTipText("");

        AddBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        AddBtn.setText("ADD");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Stock Id", "Added Date"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout AddPnlLayout = new javax.swing.GroupLayout(AddPnl);
        AddPnl.setLayout(AddPnlLayout);
        AddPnlLayout.setHorizontalGroup(
            AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddPnlLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel15)
                        .addComponent(jLabel16))
                    .addComponent(jLabel7))
                .addGap(13, 13, 13)
                .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtCompanyName)
                    .addComponent(TxtType, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtListingDate, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(116, 116, 116)
                .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11)
                        .addComponent(jLabel13)))
                .addGap(35, 35, 35)
                .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtClosePrice)
                    .addComponent(TxtTotalShares)
                    .addComponent(TxtOpenPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(170, 170, 170))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddPnlLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddPnlLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddPnlLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(27, 27, 27)
                        .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddBtn)
                            .addComponent(TxtStockId, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(366, 366, 366))))
        );
        AddPnlLayout.setVerticalGroup(
            AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPnlLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(TxtStockId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(TxtTotalShares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddPnlLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(TxtClosePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AddPnlLayout.createSequentialGroup()
                        .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TxtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(TxtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(AddPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtListingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(TxtOpenPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(AddBtn)
                .addGap(73, 73, 73)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        TabbedPanel.addTab("tab3", AddPnl);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Stock Id", "Updated Date"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        UpdateBtn.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        UpdateBtn.setText("UPDATE");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        jLabel18.setText("Open Price");

        jLabel19.setText("Listing Date");

        jLabel20.setText("Type");

        jLabel9.setText("Company Name");

        jLabel21.setText("Stock Id");

        StockIdTxt.setToolTipText("");

        jLabel22.setText("Total Shares");

        jLabel23.setText("Close Price");

        javax.swing.GroupLayout UpdatePnlLayout = new javax.swing.GroupLayout(UpdatePnl);
        UpdatePnl.setLayout(UpdatePnlLayout);
        UpdatePnlLayout.setHorizontalGroup(
            UpdatePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdatePnlLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addGroup(UpdatePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdatePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel20)
                        .addComponent(jLabel19))
                    .addComponent(jLabel9))
                .addGap(13, 13, 13)
                .addGroup(UpdatePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CompanyNameTxt)
                    .addComponent(TypeTxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ListingDateTxt, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(116, 116, 116)
                .addGroup(UpdatePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22)
                    .addGroup(UpdatePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel18)
                        .addComponent(jLabel23)))
                .addGap(35, 35, 35)
                .addGroup(UpdatePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ClosePriceTxt)
                    .addComponent(TotalSharesTxt)
                    .addComponent(OpenPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(170, 170, 170))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdatePnlLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(UpdatePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdatePnlLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdatePnlLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(27, 27, 27)
                        .addGroup(UpdatePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpdateBtn)
                            .addComponent(StockIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(366, 366, 366))))
        );
        UpdatePnlLayout.setVerticalGroup(
            UpdatePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdatePnlLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(UpdatePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(StockIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(UpdatePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdatePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(TotalSharesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UpdatePnlLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(UpdatePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(ClosePriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(UpdatePnlLayout.createSequentialGroup()
                        .addGroup(UpdatePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(CompanyNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(UpdatePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(TypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(UpdatePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ListingDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(OpenPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(UpdateBtn)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        TabbedPanel.addTab("tab2", UpdatePnl);

        HomePanel.add(TabbedPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, -60, 920, 760));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1110, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(140, 151, 157));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome To InfoStock");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Where all your Stock needs are met");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/StockIs/resource/Your paragraph text.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(9, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        LoginPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 270, 420));

        jPanel2.setBackground(new java.awt.Color(188, 204, 220));

        jLabel3.setBackground(new java.awt.Color(188, 204, 220));
        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Login To The System");

        btnLogin.setBackground(new java.awt.Color(188, 204, 220));
        btnLogin.setFont(new java.awt.Font("Helvetica Neue", 1, 17)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(188, 204, 220));
        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username");

        jLabel5.setBackground(new java.awt.Color(188, 204, 220));
        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(UsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel3)
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(UsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(PasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(btnLogin)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        LoginPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 370, 420));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/StockIs/resource/Untitled design.png"))); // NOI18N
        LoginPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(LoginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void HomeLblMouseCLicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeLblMouseCLicked
        // TODO add your handling code here:
        TabbedPanel.setSelectedIndex(0);
    }//GEN-LAST:event_HomeLblMouseCLicked

    private void AddLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddLblMouseClicked
        // TODO add your handling code here:
        TabbedPanel.setSelectedIndex(1);
    }//GEN-LAST:event_AddLblMouseClicked
 
    private void UpdateLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateLblMouseClicked
        // TODO add your handling code here:
        TabbedPanel.setSelectedIndex(2);
    }//GEN-LAST:event_UpdateLblMouseClicked

    private void DeleteLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteLblMouseClicked
        String response;
        
        response = JOptionPane.showInputDialog("Stock Id");
        
        String StockId = response;
        
       
        
        for (int i = 0; i < stockList.size(); i++) {
            stockModel existingStock = stockList.get(i);
            if (existingStock.getStockId().equals(StockId)) {
                int dialogButton = JOptionPane.YES_NO_OPTION;
                stockModel result =stockList.get(i);
                JOptionPane.showConfirmDialog(null,"Would you like to remove"+response+"\n","Warning",dialogButton);
                
                if(dialogButton == JOptionPane.YES_OPTION){
                    
                    stockList.remove(i);
                    loadListToTable(stockList);
                    JOptionPane.showMessageDialog(null,"Stock removed");
                    
                }
                else{
                    JOptionPane.showMessageDialog(null,"Stock not removed");
                }
                
                break;
            }
         }
        
        
    }//GEN-LAST:event_DeleteLblMouseClicked

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
    try {
    // Retrieving and validating inputs
    if( TxtStockId.getText().isEmpty() ||
        TxtCompanyName.getText().isEmpty() ||
        TxtType.getText().isEmpty() ||
        TxtListingDate.getText().isEmpty() ||
        TxtTotalShares.getText().isEmpty() ||
        TxtOpenPrice.getText().isEmpty() ||
        TxtClosePrice.getText().isEmpty())
        
    {
        throw new NullPointerException("Fill all the values");
    }
    
    if (!validator.validateStockId(TxtStockId.getText().trim())) 
    {
        
        throw new IllegalArgumentException("Invalid Stock ID. It must be at least 4 digits.");
    }

    
    if (!validator.validateName(TxtCompanyName.getText().trim())) 
    {
        throw new IllegalArgumentException("Invalid Company Name. It must contain only alphabets.");
    }
 
    
    if (!validator.validateType(TxtType.getText().trim())) 
    {
        throw new IllegalArgumentException("Invalid Type. Allowed values are: Equity, Ordinary, Preference, Deferred, Non-voting.");
    }

   
    if (!validator.validateListingDate(TxtListingDate.getText().trim())) 
    {
        throw new IllegalArgumentException("Invalid Listing Date. Format must be YYYY-MM-DD.");
    }

   
    if (!validator.validateTotalShares((TxtTotalShares.getText().trim()))) 
    {
        throw new IllegalArgumentException("Invalid Total Shares. It must be a positive integer.");
    }

    
    if (!validator.validateOpenPrice(TxtOpenPrice.getText().trim())) 
    {
        throw new IllegalArgumentException("Invalid Open Price. It must be a positive numeric value.");
    }


    if (!validator.validateClosePrice(TxtClosePrice.getText().trim())) 
    {
        throw new IllegalArgumentException("Invalid Close Price. It must be a positive numeric value.");
    }

    // If all validations pass, you can proceed with further operations
        String stockId = TxtStockId.getText().trim();
        String name = TxtCompanyName.getText().trim();
        String type = TxtType.getText().trim();
        String listingDate = TxtListingDate.getText().trim();
        int totalShares = Integer.parseInt(TxtTotalShares.getText().trim());
        double openPrice = Double.parseDouble(TxtOpenPrice.getText().trim());
        double closePrice = Double.parseDouble(TxtClosePrice.getText().trim());
       
        
        stockModel newStock = new stockModel(
        stockId,
        name,
        type,
        listingDate,
        totalShares,
        openPrice,
        closePrice);
        
        if(checkDuplicateStock(newStock)){
            throw new RepeatingStockIdException ("The Stock id already exists.");
        }
        else{
        stockList.add(newStock);
        loadListToTable(stockList);
        
        TxtStockId.setText("");
        TxtCompanyName.setText("");
        TxtType.setText("");
        TxtListingDate.setText("");
        TxtTotalShares.setText("");
        TxtOpenPrice.setText("");
        TxtClosePrice.setText("");
        }

} 
    catch(RepeatingStockIdException e)
    {
         JOptionPane.showMessageDialog(this, "The stock id already exists " + e.getMessage(),"Unexpected Error", JOptionPane.ERROR_MESSAGE);
    }
    catch(NullPointerException e)
    {
        JOptionPane.showMessageDialog(this, "all fields must be filled " + e.getMessage(),"Input Error", JOptionPane.ERROR_MESSAGE);
    }
    catch (NumberFormatException e) 
    {
    JOptionPane.showMessageDialog(this, "Input must be a valid number: " + e.getMessage(),"Input Error", JOptionPane.ERROR_MESSAGE);
    } 
    catch (IllegalArgumentException e) 
    {
    JOptionPane.showMessageDialog(this, "Validation Error: " + e.getMessage(),"Validation Error", JOptionPane.ERROR_MESSAGE);
    } 
    catch (Exception e) 
    {
    JOptionPane.showMessageDialog(this, "Unexpected Error: " + e.getMessage(),"Unexpected Error", JOptionPane.ERROR_MESSAGE);
    }

        
    }//GEN-LAST:event_AddBtnActionPerformed
private static class RepeatingStockIdException extends Exception {

        public RepeatingStockIdException(String the_Stock_id_already_exists) {
        }
    }
    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // TODO add your handling code here:
        try 
        {
            // Retrieving and validating inputs
            if( StockIdTxt.getText().isEmpty() ||
                CompanyNameTxt.getText().isEmpty() ||
                TypeTxt.getText().isEmpty() ||
                ListingDateTxt.getText().isEmpty() ||
                TotalSharesTxt.getText().isEmpty() ||
                OpenPriceTxt.getText().isEmpty() ||
                ClosePriceTxt.getText().isEmpty())

            {
                throw new NullPointerException("Fill all the values");
            }

            if (!validator.validateStockId(StockIdTxt.getText().trim())) 
            {

                throw new IllegalArgumentException("Invalid Stock ID. It must be at least 4 digits.");
            }


            if (!validator.validateName(CompanyNameTxt.getText().trim())) 
            {
                throw new IllegalArgumentException("Invalid Company Name. It must contain only alphabets.");
            }


            if (!validator.validateType(TypeTxt.getText().trim())) 
            {
                throw new IllegalArgumentException("Invalid Type. Allowed values are: Equity, Ordinary, Preference, Deferred, Non-voting.");
            }


            if (!validator.validateListingDate(ListingDateTxt.getText().trim())) 
            {
                throw new IllegalArgumentException("Invalid Listing Date. Format must be YYYY-MM-DD.");
            }


            if (!validator.validateTotalShares((TotalSharesTxt.getText().trim()))) 
            {
                throw new IllegalArgumentException("Invalid Total Shares. It must be a positive integer.");
            }


            if (!validator.validateOpenPrice(OpenPriceTxt.getText().trim())) 
            {
                throw new IllegalArgumentException("Invalid Open Price. It must be a positive numeric value.");
            }


            if (!validator.validateClosePrice(ClosePriceTxt.getText().trim())) 
            {
                throw new IllegalArgumentException("Invalid Close Price. It must be a positive numeric value.");
            }

            // If all validations pass, you can proceed with further operations
                String stockId = StockIdTxt.getText().trim();
                String name = CompanyNameTxt.getText().trim();
                String type = TypeTxt.getText().trim();
                String listingDate = ListingDateTxt.getText().trim();
                int totalShares = Integer.parseInt(TotalSharesTxt.getText().trim());
                double openPrice = Double.parseDouble(OpenPriceTxt.getText().trim());
                double closePrice = Double.parseDouble(ClosePriceTxt.getText().trim());


                stockModel updatedStock = new stockModel(
                stockId,
                name,
                type,
                listingDate,
                totalShares,
                openPrice,
                closePrice);

               boolean stockUpdated = false;
                for (int i = 0; i < stockList.size(); i++) {
                    stockModel existingStock = stockList.get(i);
                    if (existingStock.getStockId().equals(updatedStock.getStockId())) {
                        // Update the stock data
                        stockList.set(i, updatedStock);
                        stockUpdated = true;
                        break;
                    }
                 }
                if (!stockUpdated)
                {
                    throw new RepeatingStockIdException("The Stock ID does not exist.");
                }
                else{
                    loadListToTable(stockList);
                    
                    StockIdTxt.setText("");
                    CompanyNameTxt.setText("");
                    TypeTxt.setText("");
                    ListingDateTxt.setText("");
                    TotalSharesTxt.setText("");
                    OpenPriceTxt.setText("");
                    ClosePriceTxt.setText("");
                    
                    JOptionPane.showMessageDialog(null,"The Stock table is updated","Stock Updated",JOptionPane.INFORMATION_MESSAGE);
                }
                
                

        } 
    catch(RepeatingStockIdException e)
    {
         JOptionPane.showMessageDialog(this, "The stock id dosenot exists " + e.getMessage(),"Unexpected Error", JOptionPane.WARNING_MESSAGE);
    }
    catch(NullPointerException e)
    {
        JOptionPane.showMessageDialog(this, "all fields must be filled " + e.getMessage(),"Input Error", JOptionPane.WARNING_MESSAGE);
    }
    catch (NumberFormatException e) 
    {
    JOptionPane.showMessageDialog(this, "Input must be a valid number: " + e.getMessage(),"Input Error", JOptionPane.WARNING_MESSAGE);
    } 
    catch (IllegalArgumentException e) 
    {
    JOptionPane.showMessageDialog(this, "Validation Error: " + e.getMessage(),"Validation Error", JOptionPane.WARNING_MESSAGE);
    } 
    catch (Exception e) 
    {
    JOptionPane.showMessageDialog(this, "Unexpected Error: " + e.getMessage(),"Unexpected Error", JOptionPane.WARNING_MESSAGE);
    }

        
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        // Get the username and password input
        String username = "admin";//UsernameTxt.getText(); //txtFldLoginUsername.getText();
        String password = "admin"; //PasswordTxt.getText(); //new String(pwdFldLogin.getPassword());

        // Check if username or password is empty
        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Please fill the username and password","Empty fields",JOptionPane.INFORMATION_MESSAGE);
        } // Check if username and password are incorrect
        else if (!username.equals("admin") || !password.equals("admin")) {
            JOptionPane.showMessageDialog(null, "Username or Password dosenot Match", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        } // If credentials are correct, proceed to load the main screen
        else {
            JOptionPane.showMessageDialog(null,"Succesfully Loged In the System");
            loadScreen("HomeScreen"); // Load the main screen
        }
    }//GEN-LAST:event_btnLoginActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stockModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stockModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stockModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stockModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        StockApp stock = new StockApp();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
           stock.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JLabel AddLbl;
    private javax.swing.JPanel AddPnl;
    private javax.swing.JTextField ClosePriceTxt;
    private javax.swing.JTextField CompanyNameTxt;
    private javax.swing.JLabel DeleteLbl;
    private javax.swing.JLabel HomeLbl;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JPanel HomePnl;
    private javax.swing.JTextField ListingDateTxt;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JTextField OpenPriceTxt;
    private javax.swing.JTextField PasswordTxt;
    private javax.swing.JTextField StockIdTxt;
    private javax.swing.JTabbedPane TabbedPanel;
    private javax.swing.JTable TblStock;
    private javax.swing.JTextField TotalSharesTxt;
    private javax.swing.JTextField TxtClosePrice;
    private javax.swing.JTextField TxtCompanyName;
    private javax.swing.JTextField TxtListingDate;
    private javax.swing.JTextField TxtOpenPrice;
    private javax.swing.JTextField TxtStockId;
    private javax.swing.JTextField TxtTotalShares;
    private javax.swing.JTextField TxtType;
    private javax.swing.JTextField TypeTxt;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JLabel UpdateLbl;
    private javax.swing.JPanel UpdatePnl;
    private javax.swing.JTextField UsernameTxt;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

    
}
